name: Update audio

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Tourne toutes les heures, par exemple

jobs:
  build:
    runs-on: ubuntu-latest
    # CRUCIAL : Donne le droit à l'Action d'écrire dans ton repo
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install numpy librosa soundfile

      - name: Run machine
        run: |
          # On se place dans le dossier du script pour éviter les erreurs de chemin
          cd content/y-y2/
          python script.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # On ajoute les nouveaux fichiers générés dans le dossier outputs
          git add content/y-y2/outputs/*.wav
          # On commit seulement s'il y a des changements pour éviter les erreurs
          git commit -m "Dégradation sonore : nouvel état" || echo "Pas de changements"
          git push
