name: y = y2

on:
  schedule:
    - cron: '*/5 * * * *' # S'exécute toutes les 5 minutes
  workflow_dispatch:      # Permet de le lancer manuellement pour tester

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install numpy librosa soundfile

      - name: Run Machine
        run: python content/y-y2/script.py

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/y-y2/outputs/latest.wav
          git add content/y-y2/outputs/count.txt
          git commit -m "y-y2: mutation" || exit 0
          git push
